//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSD365VSAddIn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddinResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddinResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSD365VSAddIn.AddinResources", typeof(AddinResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Project (SS D365).
        /// </summary>
        internal static string AddToProjectMenuAddIn {
            get {
                return ResourceManager.GetString("AddToProjectMenuAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to SysOperation - Experimental (SSD365).
        /// </summary>
        internal static string ConvertToSysOperation {
            get {
                return ResourceManager.GetString("ConvertToSysOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create code extension (SS D365).
        /// </summary>
        internal static string CreateCodeExtension {
            get {
                return ResourceManager.GetString("CreateCodeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create extension (SS D365).
        /// </summary>
        internal static string CreateExtension {
            get {
                return ResourceManager.GetString("CreateExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS D365 VSAddIn .
        /// </summary>
        internal static string DesignerAddinCaption {
            get {
                return ResourceManager.GetString("DesignerAddinCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creade display menu item (SS D365).
        /// </summary>
        internal static string FormsUtilMenuItemAddin {
            get {
                return ResourceManager.GetString("FormsUtilMenuItemAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create label for properties (SS D365).
        /// </summary>
        internal static string LabelCreatorMainMenuAddIn {
            get {
                return ResourceManager.GetString("LabelCreatorMainMenuAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu caption for SSD365VSAddIn AddIn.
        /// </summary>
        internal static string MainMenuAddInCaption {
            get {
                return ResourceManager.GetString("MainMenuAddInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model settings (SS D365).
        /// </summary>
        internal static string ModelSettings {
            get {
                return ResourceManager.GetString("ModelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Inquire Security duty (SS D365).
        /// </summary>
        internal static string SecurityDutyInquireCreatorDesignContextMenuAddInCaption {
            get {
                return ResourceManager.GetString("SecurityDutyInquireCreatorDesignContextMenuAddInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Maintain Security duty (SS D365).
        /// </summary>
        internal static string SecurityDutyMaintainCreatorDesignContextMenuAddInCaption {
            get {
                return ResourceManager.GetString("SecurityDutyMaintainCreatorDesignContextMenuAddInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Maintain and view Privilege (SS D365).
        /// </summary>
        internal static string SecurityPrivilegeCreatorMenuAddInCaption {
            get {
                return ResourceManager.GetString("SecurityPrivilegeCreatorMenuAddInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS D365 AddIn Settings (SS D365).
        /// </summary>
        internal static string SettingsMainMenuCaption {
            get {
                return ResourceManager.GetString("SettingsMainMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the label (SS D365).
        /// </summary>
        internal static string ShowTheLabelMenuAddIn {
            get {
                return ResourceManager.GetString("ShowTheLabelMenuAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Form (SS D365).
        /// </summary>
        internal static string TableFormCreatorMenuAddIn {
            get {
                return ResourceManager.GetString("TableFormCreatorMenuAddIn", resourceCulture);
            }
        }
    }
}
